# Generated by Django 2.2 on 2020-06-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=150, unique=True, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'ФИО',
                'verbose_name_plural': 'ФИО',
                'ordering': ['person'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True, verbose_name='Телефон')),
                ('contact_type', models.CharField(choices=[('home', 'Домашний телефон'), ('mobile', 'Мобильный телефон')], max_length=50, verbose_name='Тип телефона')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telephone_directory.Person', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
